Repository ManthanShettigar/FunWithPython, pull requests merged in 2021-10, with the labels that each got.

#2 Added Readme file to the project
  README.md
Labels: hacktoberfest-accepted

#3 Added Password Generator
  random_password_generator/pwd_gen.py
Labels: hacktoberfest-accepted

#5 Rock Paper Scissor Game Added
  rock_paper_scissor/rps.py
Labels: hacktoberfest-accepted

#6 Modified guessthenum.py, added medium difficulty and many more
  guess_the_number/guessthenumber.py
Labels: hacktoberfest-accepted

#9 added a hangman game
  hangman/__pycache__/hangman_art.cpython-39.pyc
  hangman/__pycache__/hangman_words.cpython-39.pyc
  hangman/hangman.py
  hangman/hangman_art.py
  hangman/hangman_words.py
Labels: good first issue, hacktoberfest-accepted

#11 Added anime quote generator.
  anime_quote_generator/anime-quote.py
Labels: hacktoberfest-accepted

#12 modified rock paper scissor
  rock_paper_scissor/rps.py
Labels: enhancement, Hacktoberfest

#13 Added Hand-Gesture-Volume-Control Script
  gesture_volume_control/Readme.md
  gesture_volume_control/main.py
  gesture_volume_control/requirements.txt
Labels: hacktoberfest-accepted

#14 Adding Heart Disease Prediction
  Heart_Disease_Prediction/Heart_disease.ipynb
  Heart_Disease_Prediction/heart_disease.csv
  README.md
Labels: good first issue, hacktoberfest-accepted

#15 Added Flappy bird Game (Hacktoberfest2021)
  Flappy-Bird/Readme.md
  Flappy-Bird/flappy.py
Labels: hacktoberfest-accepted

#16 Added Dice roll stimulator
  Dice-Roll/Readme.md
  Dice-Roll/diceRoll.py
Labels: hacktoberfest-accepted

#19 Created lie_detector.py, game to detect lies
  InteractivePrograms/lie_detector.py
Labels: hacktoberfest-accepted

#20 modified the rock paper scissor game by adding a draw condition & print statement
  rock_paper_scissor/rps.py
Labels: hacktoberfest-accepted

#21 Added a treasure hunt program
  Treasure_island/Treasure_hunt.py
Labels: hacktoberfest-accepted

#23 Titanic data set
  Titanic/Titanic_Gaurang.ipynb
  Titanic/titanic.csv
Labels: hacktoberfest-accepted

#24 sudoku
  Sudoku/sudoku solver.py
Labels: hacktoberfest-accepted

#26 added a currency converter program in python
  CurrencyConv/data.txt
  CurrencyConv/main.py
Labels: hacktoberfest-accepted

#27 updating readme.md documentation
  Fun_with_Python.jpg
  README.md
Labels: hacktoberfest-accepted

#28 Added Pong Game
  ping_pong_game/pong.py
Labels: hacktoberfest-accepted

#29 Added a small python project - clock
  clock project/clock.py
Labels: hacktoberfest-accepted

#31 Added a coin flipping game (heads or tails)
  coin_flipping_game/coinflipgame.py
Labels: hacktoberfest-accepted

#33 Youtube Video Downloader
  Youtube Video Downloader/Youtube_Vid_Downloader.py
  Youtube Video Downloader/readme.md
Labels: hacktoberfest-accepted
